image: node:10.15.3
pipelines:
  branches:
    develop:
      - step:
          name: Install & Build
          caches:
            - node
          script:
            - npm install
            - export REACT_APP_API_URL=$REACT_APP_API_URL
            - export REACT_APP_VERSION=$REACT_APP_VERSION
            - export REACT_APP_AUTH_KEY=$REACT_APP_AUTH_KEY
            - export REACT_APP_COOKIE_DOMAIN=$REACT_APP_COOKIE_DOMAIN
            - export REACT_APP_X_42CADET_AUTH=$REACT_APP_X_42CADET_AUTH
            - REACT_APP_ENVIRONMENT=develop npm run test_build
          artifacts:
            - build/**
      - step:
          name: Deploy to S3
          deployment: develop
          script:
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: checkin.dev.42seoul.io
                ACL: "public-read"
                LOCAL_PATH: "build"
      - step:
          name: Invalidate Cloudfront Cache
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: E2Y9ERNT06QE7K
