image: node:16.13.0
pipelines:
  branches:
    develop:
      - step:
          name: Deploy to Develop
          deployment: Develop
          caches:
            - node
          script:
            - npm install
            - export REACT_APP_VERSION=$REACT_APP_VERSION
            - npm run release:dev
          artifacts:
            - build/**
      - step:
          name: Deploy to S3
          script:
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: checkin.dev.42seoul.io
                ACL: "public-read"
                LOCAL_PATH: "build"
      - step:
          name: Invalidate Cloudfront Cache
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: E2Y9ERNT06QE7K
    main:
      - step:
          name: Deploy to Production
          deployment: Production
          caches:
            - node
          script:
            - npm install
            - export REACT_APP_VERSION=$REACT_APP_VERSION
            - npm run release:prod
          artifacts:
            - build/**
      - step:
          name: Deploy to S3
          script:
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: checkin.42seoul.io
                ACL: "public-read"
                LOCAL_PATH: "build"
      - step:
          name: Invalidate Cloudfront Cache
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: ETIST7O39KUMO
